### ISSUE TITLE
ug! no event found for type 1058

### ISSUE THREAD

**Issue by stintel** [mchehab/rasdaemon#16]
When building rasdaemon with --disable-diskerror, logs are flooded with `ug! no event found for type 1058`. I tried to disable diskerror because otherwise my logs are flooded with `<...>-218   [041]     0.000111: block_rq_complete:    2020-05-18 23:59:59 +0300`. Unfortunately it seems this just seems to change the line that is logged.

Running rasdaemon 0.6.5 on Gentoo, kernel 5.6.13.

[rasdaemon.log](https://github.com/mchehab/rasdaemon/files/4647253/rasdaemon.log)

**Comment by mchehab** [comment]
That's weird. This event should only be enabled if DISKERROR was enabled. See ras-events.c:

```
#ifdef HAVE_DISKERROR
        rc |= __toggle_ras_mc_event(ras, "block", "block_rq_complete", enable);
#endif
```

Did you reboot your machine after re-building the rasdaemon with this option disabled?

Maybe it is still using the old config.

**Comment by mchehab** [comment]
As an update, libevent is an early version of a code that was later packaged as libtraceevent.

I updated rasdaemon to use libtraceevent after version 0.7.0. This should hopefully help solving issues when decoding events, as such library is maintained altogether with the Kernel code.
