### ISSUE TITLE
v0.8.2 release tarball

### ISSUE THREAD

**Issue by vt-alt** [mchehab/rasdaemon#183]
Many [watch files](https://salsa.debian.org/janitor-team/proposed/rasdaemon/-/blob/master/debian/watch?ref_type=heads) look for the new releases in https://www.infradead.org/~mchehab/rasdaemon/ but 0.8.2 is not there. Will it get uploaded there or that location is abandoned?

**Comment by mchehab** [comment]
Em Wed, 20 Nov 2024 16:48:37 -0800
Vitalio ***@***.***> escreveu:

> Many [watch files](https://salsa.debian.org/janitor-team/proposed/rasdaemon/-/blob/master/debian/watch?ref_type=heads) look for the new releases in https://www.infradead.org/~mchehab/rasdaemon/ but 0.8.2 is not there. Will it get uploaded there or that location is abandoned?

Forgot to update it. Tarballs should be there now.

Thanks,
Mauro

**Comment by vt-alt** [comment]
Thanks!
