### ISSUE TITLE
GitLab repo is gone (404)

### ISSUE THREAD

**Issue by TiborGY** [mchehab/rasdaemon#61]
Visiting https://gitlab.com/mchehab_kernel/rasdaemon only yields a 404 error.

**Comment by mchehab** [comment]
It is working here. Perhaps you got some transitory error?

**Comment by TiborGY** [comment]
I have just clicked the link above to make sure, and first it asked me to log in to GitLab, then it gave me the 404. Maybe the repo got set to private somehow?

**Comment by mchehab** [comment]
> I have just clicked the link above to make sure, and first it asked me to log in to GitLab, then it gave me the 404. Maybe the repo got set to private somehow?
Indeed, it got marked as private. No idea why this happened. Anyway, fixed. It should be visible again. Thanks for warning me about that!

**Comment by TiborGY** [comment]
Thanks!
