### ISSUE TITLE
negative record size -8

### ISSUE THREAD

**Issue by evils** [mchehab/rasdaemon#75]
occasionally rasdaemon will start to emit the following: `ug! negative record size -8`
it does so continuously until restarted

the journalctl -fu rasdaemon.service output will be quiet for 30 seconds, then emit something like this:

```
Nov 02 19:38:43 valix systemd-journald[686]: [🡕] Suppressed 5590251 messages from rasdaemon.service
Nov 02 19:38:43 valix rasdaemon[1009]:   ug! negative record size -8
Nov 02 19:38:43 valix rasdaemon[1009]:   ug! negative record size -8
Nov 02 19:38:43 valix rasdaemon[1009]:   ug! negative record size -8
```

strace seems to indicate it is continuously writing that message
```
20:08:34.341449 write(2, "ug! negative record size -8", 27) = 27 <0.000008>
20:08:34.341476 write(2, "\n", 1)       = 1 <0.000008>
20:08:34.341505 write(1, "\n", 1)       = 1 <0.000009>
20:08:34.341534 write(2, "  ", 2)       = 2 <0.000009>
20:08:34.341563 write(2, "ug! negative record size -8", 27) = 27 <0.000009>
20:08:34.341593 write(2, "\n", 1)       = 1 <0.000008>
20:08:34.341625 write(1, "\n", 1)       = 1 <0.000023>
20:08:34.341674 write(2, "  ", 2)       = 2 <0.000009>
20:08:34.341704 write(2, "ug! negative record size -8", 27) = 27 <0.000009>
20:08:34.341733 write(2, "\n", 1)       = 1 <0.000008>
20:08:34.341763 write(1, "\n", 1)       = 1 <0.000008>
20:08:34.341792 write(2, "  ", 2)       = 2 <0.000009>
```

this is on rasdaemon 0.6.8, default configuration besides setting mainboard and DIMM labels, on nixos-unstable

i still get the seemingly spurious errors reported in #10 but the reported number did not increase in a 1 minute interval

ordering systemd to restart rasdaemon results in the following after about 1:30 minutes
```
Nov 02 20:11:45 valix systemd[1]: rasdaemon.service: State 'stop-sigterm' timed out. Killing.
Nov 02 20:11:45 valix systemd[1]: rasdaemon.service: Killing process 1009 (rasdaemon) with signal SIGKILL.
Nov 02 20:11:45 valix systemd[1]: rasdaemon.service: Main process exited, code=killed, status=9/KILL
Nov 02 20:11:45 valix systemd[1]: rasdaemon.service: Failed with result 'timeout'.
Nov 02 20:11:45 valix systemd[1]: Stopped the RAS logging daemon.
Nov 02 20:11:45 valix systemd[1]: rasdaemon.service: Consumed 23h 53min 47.734s CPU time, read 2.0M from disk, written 27.6G to disk, no IP traffic.
Nov 02 20:11:45 valix systemd[1]: Started the RAS logging daemon.
Nov 02 20:11:45 valix rasdaemon[3357308]: Can't get traces from ras:memory_failure_event
```

my workstation's power usage rose about 30W when rasdaemon gots into this faulty mode
![image](https://user-images.githubusercontent.com/30512529/199603487-133c057a-6713-47ab-b7e6-bb8f3187ea7d.png)
though dropped only ~15W after restarting rasdaemon

the horizontal lines in this graph are sections where the computer is in sleep mode (no data), this shows the issue did not start at such a boundary, and persists across them

**Comment by adamcstephens** [comment]
I'm experiencing this as well on nixos 22.11. My journal is filled with these messages.

```
─❯ journalctl | rg "negative record size" | wc -l
14153194
```

**Comment by mchehab** [comment]
This error is part of the trace library, and not at rasdaemon itself. It could be due to some errors that may already be fixed, so I opted to just remove our fork of the library, using the upstream version:

https://github.com/mchehab/rasdaemon/commit/4c0ef52cf26925e1e01019b4b64bfb3ce3cd8c14

Hopefully, this should address the issue.
