### ISSUE TITLE
When SELinux is enabled, ras-mc-ctl.service fails to be started

### ISSUE THREAD

**Issue by xiaoge1001** [mchehab/rasdaemon#79]
Reproduction procedure:

dnf install -y rasdaemon
setenforce 1
systemctl start ras-mc-ctl.service
systemctl status ras-mc-ctl.service

This problem occurs in my machine, but I don't get valuable output error information. Why does the service fail to be started?

**Comment by xiaoge1001** [comment]
I don't know why. I temporarily use the following method to avoid it. Is this the right? What's the risk?

https://gitee.com/src-openeuler/rasdaemon/blob/c2d3dc48710e7958919ad8166123a39c0332f1cc/fix-ras-mc-ctl.service-startup-failed-when-selinux-is-no.patch

**Comment by mchehab** [comment]
It seems to be a distro-specific issue. Perhaps some permissions are missing for rasdaemon at the selinux policies.

**Comment by im-0** [comment]
I was able to figure out what is going on. Please see https://github.com/fedora-selinux/selinux-policy/pull/2055 and https://github.com/mchehab/rasdaemon/pull/148
