### ISSUE TITLE
0.6.5 released or not?

### ISSUE THREAD

**Issue by HRio** [mchehab/rasdaemon#8]
Can not see a 0.6.5 tag in this repo but a 0.6.5 tar.gz is uploaded here:
https://www.infradead.org/~mchehab/rasdaemon/

**Comment by mchehab** [comment]
Em Fri, 13 Dec 2019 00:36:59 -0800
Henrik Riomar <notifications@github.com> escreveu:

> Can not see a 0.6.5 tag in this repo but a 0.6.5 tar.gz is uploaded here:
> https://www.infradead.org/~mchehab/rasdaemon/
> 

Yes, it was released. I just forgot to push the tags back to the repos.

Just pushed them.


Cheers,
Mauro

**Comment by HRio** [comment]
thanks
